# Generated by Django 4.0.4 on 2022-04-29 09:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='data',
            options={},
        ),
        migrations.AlterModelOptions(
            name='lab',
            options={},
        ),
    ]
