# Generated by Django 2.2.12 on 2022-05-03 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='data',
            name='published',
            field=models.BooleanField(default=False),
        ),
    ]
