# Generated by Django 4.0.4 on 2022-04-29 02:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0004_alter_data_age'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female')], default='', max_length=1),
        ),
        migrations.AlterField(
            model_name='lab',
            name='sample_number',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='labform', to='form.data'),
        ),
    ]
