# Generated by Django 2.2.12 on 2022-04-29 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0007_alter_data_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='gender',
            field=models.CharField(default='', max_length=1),
        ),
        migrations.AlterField(
            model_name='data',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
